/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rgb;

import efeitos.efeitoOnda;
import efeitos.efeitoDecremental;
import efeitos.efeitoMusica;
import efeitos.efeitoPorImagemDaTela;
import efeitos.efeitoArcoIris;
import efeitos.efeitoStrobol;
import ca.fiercest.aurasdk.AuraSDK;
import ca.fiercest.aurasdk.Color;
import com.logitech.gaming.LogiLED;
import java.awt.AWTException;
import java.awt.MenuItem;
import java.awt.PopupMenu;
import java.awt.SystemTray;
import java.awt.TrayIcon;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;



/**
 *
 * @author Claud
 */
public class principal extends javax.swing.JFrame {
AuraSDK AsusAura;
static TrayIcon trayIcon;
efeitoDecremental efeitoDecremental;
efeitoStrobol efeitoStrobol;
efeitoArcoIris efeitoArcoIris;
efeitoOnda efeitoOnda;
efeitoMusica efeitomMusica;
efeitoPorImagemDaTela efeitoPorImagem;
    /**
     * Creates new form principal
     */
    public principal(){      
         initComponents();             
         AsusAura = new AuraSDK();  
         LogiLED.LogiLedInit(); 
         Color cor = new Color(255, 0,0);         
         AsusAura.setAllColors(cor);          
         LogiLED.LogiLedSetLighting(cor.getR(),cor.getG(),cor.getB());    
         this.setVisible(true);
         jColor.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnEfeitoMusica = new javax.swing.JButton();
        btnEfeitoOnda = new javax.swing.JButton();
        btnEfeitoArcoIris = new javax.swing.JButton();
        btnEfeitoStroob = new javax.swing.JButton();
        btnEfeitoDecremental = new javax.swing.JButton();
        btnAplicarCorSelecionada = new javax.swing.JButton();
        btnEfeitoPorImagemNaTela = new javax.swing.JButton();
        jColor = new javax.swing.JColorChooser();
        btnSair = new javax.swing.JButton();
        btnHide = new javax.swing.JButton();
        btnMinimizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);
        setName("RGBPrincipal"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEfeitoMusica.setText("Musica");
        btnEfeitoMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEfeitoMusicaActionPerformed(evt);
            }
        });
        jPanel1.add(btnEfeitoMusica);

        btnEfeitoOnda.setText("Onda");
        btnEfeitoOnda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEfeitoOndaActionPerformed(evt);
            }
        });
        jPanel1.add(btnEfeitoOnda);

        btnEfeitoArcoIris.setText("Arco Iris");
        btnEfeitoArcoIris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEfeitoArcoIrisActionPerformed(evt);
            }
        });
        jPanel1.add(btnEfeitoArcoIris);

        btnEfeitoStroob.setText("Stroob");
        btnEfeitoStroob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEfeitoStroobActionPerformed(evt);
            }
        });
        jPanel1.add(btnEfeitoStroob);

        btnEfeitoDecremental.setText("Decremental");
        btnEfeitoDecremental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEfeitoDecrementalActionPerformed(evt);
            }
        });
        jPanel1.add(btnEfeitoDecremental);

        btnAplicarCorSelecionada.setText("Aplicar");
        btnAplicarCorSelecionada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplicarCorSelecionadaActionPerformed(evt);
            }
        });
        jPanel1.add(btnAplicarCorSelecionada);

        btnEfeitoPorImagemNaTela.setText("Imagem");
        btnEfeitoPorImagemNaTela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEfeitoPorImagemNaTelaActionPerformed(evt);
            }
        });
        jPanel1.add(btnEfeitoPorImagemNaTela);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 660, 120));

        jColor.removeChooserPanel(jColor.getChooserPanels()[4]);
        jColor.removeChooserPanel(jColor.getChooserPanels()[3]);
        jColor.removeChooserPanel(jColor.getChooserPanels()[2]);
        jColor.removeChooserPanel(jColor.getChooserPanels()[0]);
        jColor.getPreviewPanel().setVisible(false);
        getContentPane().add(jColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, 420));

        btnSair.setBackground(new java.awt.Color(60, 63, 255,0));
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/m_fechar.png"))); // NOI18N
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, 30, 30));

        btnHide.setBackground(new java.awt.Color(60, 63, 255,0));
        btnHide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/m_hide.png"))); // NOI18N
        btnHide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHideActionPerformed(evt);
            }
        });
        getContentPane().add(btnHide, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 30, 30));

        btnMinimizar.setBackground(new java.awt.Color(60, 63, 255,0));
        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/m_minimize.png"))); // NOI18N
        btnMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 30, 30));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAplicarCorSelecionadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplicarCorSelecionadaActionPerformed
      pararEfeito();
            java.awt.Color nova = jColor.getSelectionModel().getSelectedColor();            
            Color cor = new Color(nova.getRed(), nova.getGreen(), nova.getBlue());         
            AsusAura.setAllColors(cor);             
            LogiLED.LogiLedSetLighting(cor.getR(),cor.getG(),cor.getB());   
            
            
         
    }//GEN-LAST:event_btnAplicarCorSelecionadaActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.dispose();
        pararEfeito();
        AsusAura.ReleaseControl();        
        LogiLED.LogiLedShutdown();
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnHideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHideActionPerformed
        tray();
    }//GEN-LAST:event_btnHideActionPerformed

    private void btnEfeitoDecrementalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEfeitoDecrementalActionPerformed
    pararEfeito();
    efeitoDecremental = new efeitoDecremental(jColor,AsusAura);    
        Thread th = new Thread(efeitoDecremental);
        th.start();      
      
    }//GEN-LAST:event_btnEfeitoDecrementalActionPerformed

    private void btnEfeitoStroobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEfeitoStroobActionPerformed
    pararEfeito();
    efeitoStrobol = new efeitoStrobol(AsusAura);    
        Thread th = new Thread(efeitoStrobol);
        th.start(); 
    
    }//GEN-LAST:event_btnEfeitoStroobActionPerformed

    private void btnEfeitoArcoIrisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEfeitoArcoIrisActionPerformed
      pararEfeito(); 
    efeitoArcoIris = new efeitoArcoIris(AsusAura);    
        Thread th = new Thread(efeitoArcoIris);
        th.start(); 
    }//GEN-LAST:event_btnEfeitoArcoIrisActionPerformed

    private void btnEfeitoOndaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEfeitoOndaActionPerformed
      pararEfeito();
    efeitoOnda = new efeitoOnda(AsusAura);
    Thread th = new Thread(efeitoOnda);
        th.start(); 
    }//GEN-LAST:event_btnEfeitoOndaActionPerformed

    private void btnEfeitoMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEfeitoMusicaActionPerformed
        pararEfeito();
        efeitomMusica = new efeitoMusica(AsusAura);
        Thread th = new Thread(efeitomMusica);
        th.start(); 
    }//GEN-LAST:event_btnEfeitoMusicaActionPerformed

    private void btnMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizarActionPerformed
       this.setState(ICONIFIED);
    }//GEN-LAST:event_btnMinimizarActionPerformed

    private void btnEfeitoPorImagemNaTelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEfeitoPorImagemNaTelaActionPerformed
        pararEfeito();
        efeitoPorImagem = new efeitoPorImagemDaTela(AsusAura);
        Thread th = new Thread(efeitoPorImagem);
        th.start(); 
       
    }//GEN-LAST:event_btnEfeitoPorImagemNaTelaActionPerformed
    
    
       
    
    private void tray(){
        this.dispose();        
        trayIcon=new TrayIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico.png")).getImage());
        trayIcon.setToolTip("RGB");       
        final SystemTray tray = SystemTray.getSystemTray();
        final PopupMenu menu =  new PopupMenu();
        MenuItem abrir = new MenuItem("Abrir");
        MenuItem exit = new MenuItem("Sair");        
        menu.add(abrir);
        menu.addSeparator();
        menu.add(exit);
        
        trayIcon.addActionListener( new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
              show();
              tray.remove(trayIcon);
            }
        });
        
        abrir.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                show();
                tray.remove(trayIcon);
            }
        });
        
        exit.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                pararEfeito();
                AsusAura.ReleaseControl();        
                LogiLED.LogiLedShutdown();
               System.exit(0);
            }
        });
        
        
        trayIcon.setPopupMenu(menu);
    try {
        tray.add(trayIcon);
    } catch (AWTException ex) {
        Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
    }
    }  

    
    public void pararEfeito(){
         try{
       efeitoArcoIris.allDone=true;         
        }catch(Exception ex){        
        }
         try{
         efeitoDecremental.allDone=true;  
          }catch(Exception ex){        
        }
         try{
        efeitoStrobol.allDone=true; 
         }catch(Exception ex){        
        }
         try{
             efeitoOnda.allDone=true;
         }catch(Exception ex){
             
         }
         try{
             efeitomMusica.allDone=true;
         }catch(Exception ex){             
         }
           try{
             efeitoPorImagem.allDone=true;
         }catch(Exception ex){             
         }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAplicarCorSelecionada;
    private javax.swing.JButton btnEfeitoArcoIris;
    private javax.swing.JButton btnEfeitoDecremental;
    private javax.swing.JButton btnEfeitoMusica;
    private javax.swing.JButton btnEfeitoOnda;
    private javax.swing.JButton btnEfeitoPorImagemNaTela;
    private javax.swing.JButton btnEfeitoStroob;
    private javax.swing.JButton btnHide;
    private javax.swing.JButton btnMinimizar;
    private javax.swing.JButton btnSair;
    private javax.swing.JColorChooser jColor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}